# Generated by Django 3.2.24 on 2024-03-04 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ["PAYMENT_GATEWAY", "Payment Gateways"],
                            ["SHIPPING_PROVIDER", "Shipping Providers"],
                            ["ANALYTICS_SERVICE", "Analytics Services"],
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.JSONField()),
                (
                    "shop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_shop",
                        to="shop.shop",
                    ),
                ),
            ],
        ),
    ]
