# Generated by Django 3.2.24 on 2024-03-04 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("performance_metrics", models.JSONField()),
                ("sales_reports", models.JSONField()),
                ("customer_insights", models.JSONField()),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopanalytics_shop",
                        to="shop.shop",
                    ),
                ),
            ],
        ),
    ]
