# Generated by Django 3.2.24 on 2024-03-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_info',
        ),
    ]
